# Generated by Django 5.0.2 on 2024-03-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiryform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(verbose_name=12)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
